import { Vazirmatn } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { dir } from "i18next";

// Configure fonts
const vazirmatn = Vazirmatn({ subsets: ["arabic"], weight: ["400", "700"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  // Example: Set language and direction (adjust 'en' or 'ar' as needed)
  const language = "en"; // Change to 'ar' for Arabic/RTL
  const direction = dir(language);

  return (
    <html lang="en" className="">
      <body
        className={`${inter.className} bg-gradient-to-bl from-surface via-background to-secondary-light`}
      >
        {children}
      </body>
    </html>
  );
}
